title: "Tymianox' Den"
description: "the den of forgotten poetry"
baseurl: "" # leave blank for GitHub Pages
url: "https://tymianox.github.io/tymianoxtheforgotten/"

markdown: kramdown
theme: null

# Optional: enable collections if you want a non-post folder later
collections:
  poetry:
    output: true
    permalink: /poem/:slug/

defaults:
    values:
      layout: poem